heal/urls.py
from django.urls import path

from . import views
app_name = "heal"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("makepost", views.makepost, name="makepost"),
    path("community", views.community, name="community"),
    path('edit_post/', views.edit_post),
    path("profile/<int:userid>", views.profile, name="profile"),
]

healthcircle/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("heal.urls")),
]

urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.urls import path

from . import views
app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register")
]

heal/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

class UserPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    content = models.CharField(max_length=120)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.content} by {self.user}"

heal/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from .models import *


def index(request):
    return render(request, "heal/index.html")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("heal:index"))
        else:
            return render(request, "heal/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "heal/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("heal:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "heal/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "heal/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("heal:index"))
    else:
        return render(request, "heal/register.html")

def community(request):
    if request.user is None:
        return HttpResponseRedirect(reverse("heal:login"))
    post_list = UserPost.objects.all().order_by('-timestamp')
    page = request.GET.get('page', 1)
    paginator = Paginator(post_list, 10)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, "heal/community.html", {
        "posts": posts,
        "curruser": request.user,
    })

@login_required
@csrf_exempt
def edit_post(request):
    if request.method == "POST":
        post_id = request.POST.get('id')
        new_post = request.POST.get('post')
        post = UserPost.objects.get(id=post_id)
        post.content = new_post
        post.save()
        try:
            post = UserPost.objects.get(id=post_id)
            if post.user == request.user:
                post.post = new_post.strip()
                post.save()
                return JsonResponse({}, status=201)
        except:
            return JsonResponse({}, status=404)

    return JsonResponse({}, status=400)

def makepost(request):
    if request.user is None:
        return HttpResponseRedirect(reverse("heal:login"))
    if request.method =="POST":
        postreq = request.POST["content"]
        p = UserPost(user=request.user, content=postreq)
        p.save()
    return HttpResponseRedirect(reverse("heal:community"))

def profile(request, userid):
    if request.user is None:
        return HttpResponseRedirect(reverse("heal:login"))
    user = User.objects.all().filter(pk=userid)[0]
    return render(request, "heal/profile.html", {
        "user": request.user,
        "profuser": user,
        "posts": UserPost.objects.all().filter(user=user).order_by('-timestamp')
    })

main/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import User


def index(request):
    return render(request, "main/index.html")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "main/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "main/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "main/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "main/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "main/register.html")

heal/templates/heal/community.html
{% extends "heal/layout.html" %}
{% block title %}Community{% endblock %}
{% block body %}
{% if user.is_authenticated %}
    <div class="w3-container w3-purple" style="margin-bottom:10px;margin-top:3%">
      <div class="row">
        <div class="col-sm-1">
        </div>
        <div class="col-sm-10">
          <h1>Create a New Post</h1>
        </div>
        <div class="col-sm-1">
        </div>
      </div>
      <div class="row">
        <div class="col-lg-1">
        </div>
        <div class="col-lg-10">
          <form  action="{% url 'heal:makepost' %}" method="post">
            {% csrf_token %}
            <input class="form-control input-lg" name="content" type="text">
            <input type="submit" class="btn btn-secondary" style="margin-top:5px;margin-bottom:10px">
          </form>
        </div>
        <div class="col-lg-1">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm-1">
        </div>
        <div class="col-sm-10">
          {% for post in posts %}
            <div class ="row">
              <div class ="col-sm-10">
                <h6><a href="{% url 'heal:profile' post.user.pk %}">{{ post.user }} </a></h6>
              </div>
              {% if post.user == curruser %}
                <div class ="col-sm">
                  <button class="btn btn-primary" id="button-{{post.id}}" data-id='{{ post.id }}'>Edit</button>
                </div>
              {% endif %}
            </div>
            <p id="post-{{post.id}}">{{ post.content }}</p>
            <textarea data-id="{{post.id}}" id="post-edit-{{post.id}}" style="display:none;" class="form-control textarea" row="3">{{post.content}}</textarea>
            <p style="color:grey">{{ post.timestamp }}</p>
            <hr>
          {% endfor %}

        </div>
        <div class="col-sm-1">
        </div>
      </div>
    </div>
    {% if posts.has_other_pages %}
      <nav aria-label="..." style="margin-left:41%">
        <ul class="pagination">
          {% if posts.has_previous %}
            <li class="page-item"><a  class="page-link" href="?page={{ posts.previous_page_number }}" tabindex="-1" aria-disabled="false">Previous</a></li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
          {% endif %}
          {% for i in posts.paginator.page_range %}
            {% if posts.number == i %}
            <li class="page-item active" aria-current="page">
              <a class="page-link" >{{ i }} <span class="sr-only">(current)</span></a>
            </li>
            {% else %}
              <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}
          {% if posts.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" aria-disabled="true">Next</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}

  {% else %}
  <div class="section-container" style="margin-top:5%">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="text-center">
            <h2>Please Log in to View Posts</h2>
          </div>
       </div>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-2">
      <a href="{% url 'heal:register' %}"><input class="btn btn-primary btn-lg" type="submit" style="margin-left:35%" value="Signup"></a>
    </div>
    <div class="col-md-2">
      <a href="{% url 'heal:login' %}"><input class="btn btn-primary btn-lg" type="submit" style="margin-left:35%" value="Login"></a>
    </div>
    <div class="col-md-4">
    </div>
  </div>
  {% endif %}
{% endblock %}

heal/templates/heal/index.html
{% extends "heal/layout.html" %}
{% block title %}Home Page{% endblock %}
{% block body %}
  <br>
  <div class="row">
    <div class="col-lg-12" >
      <img src="/static/heal/title.png" id="title_image" alt="title" style="width:100%"/>
    </div>
  </div>

  <div class="section-container" style="margin-top:5%">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="text-center">
            <h2>About Us</h2>
            <p>We are blah blah and we do blah blah. Lol</p>
          </div>
       </div>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-2">
      <a href="{% url 'heal:register' %}"><input class="btn btn-primary btn-lg" type="submit" style="margin-left:35%" value="Signup"></a>
    </div>
    <div class="col-md-2">
      <a href="{% url 'heal:login' %}"><input class="btn btn-primary btn-lg" type="submit" style="margin-left:35%" value="Login"></a>
    </div>
    <div class="col-md-4">
    </div>
  </div>


{% endblock %}

heal/templates/heal/layout.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script type="text/javascript" src="/static/heal/script.js"></script>
    <link href="{% static 'heal/styles.css' %}" rel="stylesheet" />
  </head>

  <body>
    <div class="topnav" id="myTopnav">
          <a id="home" href="{% url 'heal:index' %}" class="active">Home</a>
          <a href="{% url 'heal:community' %}">Community</a>
          <a href="#">Message</a>
          <a href="#">Contact</a>
          <div class="topnav-right">
            {% if user.is_authenticated %}
              <a href="{% url 'heal:logout' %}">Log Out</a>
            {% else %}
              <a href="{% url 'heal:register' %}">Sign Up</a>
              <a href="{% url 'heal:login' %}">Login</a>
            {% endif %}
          </div>
          <a href="javascript:void(0);" class="icon" onclick="myFunction()">
            <i class="fa fa-bars"></i>
          </a>
    </div>

    {% block body %}
    {% endblock %}
    <footer class="page-footer font-small unique-color-dark">

      <div style="background-color:#a6a6a6">
        <div class="container">

          <!-- Grid row-->
          <div class="row py-4 d-flex align-items-center">

            <!-- Grid column -->
            <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
              <h6 class="mb-0">Get connected with us on social networks!</h6>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-6 col-lg-7 text-center text-md-right">

              <!--Facebook-->
              <button type="button" class="btn btn-fb"><i class="fa fa-facebook left"></i></button>
              <!--Twitter-->
              <button type="button" class="btn btn-tw"><i class="fa fa-twitter left"></i></button>
              <!--Google +-->
              <button type="button" class="btn btn-gplus"><i class="fa fa-google-plus left"></i></button>
              <!--Linkedin-->
              <button type="button" class="btn btn-li"><i class="fa fa-linkedin left"></i></button>
              <!--Instagram-->
              <button type="button" class="btn btn-ins"><i class="fa fa-instagram left"></i></button>

            </div>
            <!-- Grid column -->

          </div>
          <!-- Grid row-->

        </div>
      </div>
    </footer>
  </body>

</html>

heal/templates/heal/login.html
{% extends "heal/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'heal:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'heal:register' %}">Register here.</a>

{% endblock %}

heal/templates/heal/profile.html
{% extends "network/layout.html" %}

{% block style %}
button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
}

button:hover, a:hover {
  opacity: 0.7;
}
{% endblock %}

{% block body %}
    <div class="container">
      <div class="row">
        <div class="col-lg">
        </div>
        <div class="col-lg" style="margin-top: 25px">
          
          <h1>{{ profuser.username }}</h1>
          <p>Followers: {{ numfr }}</p>
          <div class="row">
            <div class="col-6">
              <p><a href="{% url 'follow' profuser.pk %}"><button >Follow</button></a></p>
            </div>
            <div class="col-6">
              <p><a href="{% url 'unfollow' profuser.pk %}"><button >Unfollow</button></a></p>
            </div>
          </div>
        </div>
        <div class="col-lg">
        </div>
      </div>
      <div class="row">
        <div class="col-lg-2">
        </div>
        <div class="col-lg-8">
          <h3>{{ profuser.username }}'s posts</h3>
        </div>
        <div class="col-lg-2">
        </div>
      </div>
      <div class="row">
        <div class="col-lg-2">
        </div>
        <div class="col-lg-8">
          {% for post in posts %}
            <h5>{{ post.user }}</h5>
            {{ post.content }}
            <p style="color:grey">{{ post.timestamp }}</p>
            <hr>
          {% endfor %}
        </div>
        <div class="col-lg-2">
        </div>
      </div>
    </div>

{% endblock %}

heal/templates/heal/register.html
{% extends "heal/layout.html" %}
{% block title %}Register{% endblock %}
{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'heal:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'heal:login' %}">Log In here.</a>

{% endblock %}

main/templates/main/index.html
{% extends "main/layout.html" %}
{% block title %}Home Page{% endblock %}
{% block body %}
TODO
{% endblock %}

main/templates/main/layout.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script type="text/javascript" src="/static/main/script.js"></script>
    <link href="{% static 'main/styles.css' %}" rel="stylesheet" />
  </head>

  <body>
    <div class="topnav" id="myTopnav">
          <a id="home" href="{% url 'main:index' %}" class="active">Home</a>
          <a href="#">Community</a>
          <a href="#">Message</a>
          <a href="#">About/Contact</a>
          <div class="topnav-right">
            {% if user.is_authenticated %}
              <a href="{% url 'main:logout' %}">Log Out</a>
            {% else %}
              <a href="{% url 'main:register' %}">Sign Up</a>
              <a href="{% url 'main:login' %}">Login</a>
            {% endif %}
          </div>
          <a href="javascript:void(0);" class="icon" onclick="myFunction()">
            <i class="fa fa-bars"></i>
          </a>
    </div>

    {% block body %}
    {% endblock %}
  </body>
</html>

main/templates/main/login.html
{% extends "main/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'main:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'main:register' %}">Register here.</a>

{% endblock %}

main/templates/main/register.html
{% extends "main/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'main:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'main:login' %}">Log In here.</a>

{% endblock %}